name: Build

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout
      - uses: actions/checkout@main

      # Docker build
      - name: Load docker cache
        id: cache
        uses: actions/cache@v3
        with:
          path: build-cache.tar
          key: ${{ runner.os }}-build-cache

      - name: Docker load
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load -i build-cache.tar

      - name: Build a docker image
        run: docker build . -t session --cache-from session

      - name: Docker save
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker save session -o build-cache.tar

      - run: mkdir $GITHUB_WORKSPACE/session-build

      - name: Run a docker build
        run: docker run -v $GITHUB_WORKSPACE/session-build:/root/src/out session

      # Release
      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: $GITHUB_WORKSPACE/session-build/all.tar.gz
