name: Tag

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - run: git tag v-$GITHUB_SHA HEAD
      - run: git push origin v-$GITHUB_SHA
