name: Tag

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@main
      - name: Tag a commit
        run: git tag v-$GITHUB_SHA HEAD
      - name: Push
        run: git push origin v-$GITHUB_SHA
